name: Install NGINX
on:
    workflow_dispatch:
    push:
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: Configure the SSH Private Key Secret
              env:
                SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
              run: |
                mkdir -p ~/.ssh
                echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
                chmod 600 ~/.ssh/id_rsa
            - name: Set Strict Host Key Checking
              run: echo "StrictHostKeyChecking no" > ~/.ssh/config
            - name: Install NGINX
              env: 
                MY_HOST: ${{ secrets.AKAMAI_INSTANCE_IP_ADDRESS }}
              run: |
                ssh -i ~/.ssh/id_rsa root@"$MY_HOST" sudo apt update
                ssh -i ~/.ssh/id_rsa root@"$MY_HOST" sudo apt install -y nginx
